### ISSUE TITLE
How to feed in Amazon data?

### ISSUE THREAD

**Issue by RichardShea** [DaShenZi721/MHP#1]
Hi, 

I'm trying to replicate the results in your paper using the cited Amazon data, but having trouble figuring out the data structure that is required.  

I'm pulling the Amazon data from [Per-category files](http://jmcauley.ucsd.edu/data/amazon/links.html) which matches the source in your references.  

Do you have any documentation on how to feed the data into the [preprocess.py](https://github.com/DaShenZi721/MHP/blob/main/preprocess.py)?

I even tried the [MHP.py](https://github.com/DaShenZi721/MHP/blob/main/MHP.py) file directly with no luck.  

Thank you,

-Richard

**Comment by DaShenZi721** [comment]
Hi, @RichardShea 
Thank you for reading my paper!
I have uploaded the processed dataset of the Amazon data and updated the README. You can follow it.
